#服务端口
#dubbo发布服务
#solr
server:
  port: 9091
dubbo:
  application:
    name: search_service
  registry:
    address: zookeeper://192.168.227.130:2181
  protocol:
    name: dubbo
    port: 20881
  provider:
    timeout: 10000
    retries: 5
spring:
  data:
    solr:
      host: http://192.168.227.130:8080/solr
  rabbitmq:
    host: 192.168.227.130
    username: admin
    password: admin
    virtual-host: /admin