server:
  port: 8085
spring:
  redis:
    host: 192.168.227.130
    password: root
dubbo:
  application:
    name: cart_web
  registry:
    address: zookeeper://192.168.227.130:2181
  consumer:
    check: false