server:
  port: 8082
spring:
  data:
    solr:
      host: http://192.168.227.130:8080/solr
dubbo:
  application:
    name: search_web
  registry:
    address: zookeeper://192.168.227.130:2181
  consumer:
    check: false

